### PR TITLE
Add CPP version of selection sort

### LINKED ISSUE #541: CI failing silently
#### Description of the problem

Check logs - https://pipelines.actions.githubusercontent.com/serviceHosts/bcbe7353-57a3-4f7b-9841-e13324ebedee/_apis/pipelines/1/runs/214/signedlogcontent/5?urlExpires=2023-07-11T19%3A43%3A47.4660162Z&urlSigningMethod=HMACV1&urlSignature=ZqxVdwdbC7vEpbftgAvTKFjslTAZUk3nRSQS9m%2F%2BoHo%3D

```zsh
2023-07-11T19:36:00.1102844Z ============================= test session starts ==============================
2023-07-11T19:36:00.1103934Z platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
2023-07-11T19:36:00.1104646Z rootdir: /home/runner/work/pydatastructs/pydatastructs
2023-07-11T19:36:00.1105367Z plugins: anyio-3.7.1, cov-4.1.0
2023-07-11T19:36:00.1106205Z collected 98 items / 23 errors
2023-07-11T19:36:00.1108175Z 
2023-07-11T19:36:00.1108500Z ==================================== ERRORS ====================================
2023-07-11T19:36:00.1109293Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_algorithms.py _
2023-07-11T19:36:00.1109856Z import file mismatch:
2023-07-11T19:36:00.1163092Z imported module 'pydatastructs.graphs.tests.test_algorithms' has this __file__ attribute:
2023-07-11T19:36:00.1163650Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/graphs/tests/test_algorithms.py
2023-07-11T19:36:00.1164020Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1164595Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_algorithms.py
2023-07-11T19:36:00.1165768Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1166552Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_list.py _
2023-07-11T19:36:00.1167496Z import file mismatch:
2023-07-11T19:36:00.1168124Z imported module 'pydatastructs.graphs.tests.test_adjacency_list' has this __file__ attribute:
2023-07-11T19:36:00.1168889Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/graphs/tests/test_adjacency_list.py
2023-07-11T19:36:00.1276669Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1277247Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_list.py
2023-07-11T19:36:00.1277652Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1278131Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_matrix.py _
2023-07-11T19:36:00.1278436Z import file mismatch:
2023-07-11T19:36:00.1278824Z imported module 'pydatastructs.graphs.tests.test_adjacency_matrix' has this __file__ attribute:
2023-07-11T19:36:00.1279221Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/graphs/tests/test_adjacency_matrix.py
2023-07-11T19:36:00.1279563Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1280069Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_matrix.py
2023-07-11T19:36:00.1280483Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1280928Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_trie.py _
2023-07-11T19:36:00.1281219Z import file mismatch:
2023-07-11T19:36:00.1281959Z imported module 'pydatastructs.strings.tests.test_trie' has this __file__ attribute:
2023-07-11T19:36:00.1282350Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/strings/tests/test_trie.py
2023-07-11T19:36:00.1282659Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1283150Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_trie.py
2023-07-11T19:36:00.1283538Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1283986Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_algorithms.py _
2023-07-11T19:36:00.1284266Z import file mismatch:
2023-07-11T19:36:00.1284637Z imported module 'pydatastructs.strings.tests.test_algorithms' has this __file__ attribute:
2023-07-11T19:36:00.1285015Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/strings/tests/test_algorithms.py
2023-07-11T19:36:00.1285330Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1285811Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_algorithms.py
2023-07-11T19:36:00.1286215Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1286668Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_misc_util.py _
2023-07-11T19:36:00.1286962Z import file mismatch:
2023-07-11T19:36:00.1287339Z imported module 'pydatastructs.utils.tests.test_misc_util' has this __file__ attribute:
2023-07-11T19:36:00.1287721Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/utils/tests/test_misc_util.py
2023-07-11T19:36:00.1288030Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1288486Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_misc_util.py
2023-07-11T19:36:00.1288874Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1289327Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_code_quality.py _
2023-07-11T19:36:00.1289832Z import file mismatch:
2023-07-11T19:36:00.1290407Z imported module 'pydatastructs.utils.tests.test_code_quality' has this __file__ attribute:
2023-07-11T19:36:00.1290786Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/utils/tests/test_code_quality.py
2023-07-11T19:36:00.1291094Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1291577Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_code_quality.py
2023-07-11T19:36:00.1291984Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1292492Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_algorithms.py _
2023-07-11T19:36:00.1292791Z import file mismatch:
2023-07-11T19:36:00.1293206Z imported module 'pydatastructs.linear_data_structures.tests.test_algorithms' has this __file__ attribute:
2023-07-11T19:36:00.1293634Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/linear_data_structures/tests/test_algorithms.py
2023-07-11T19:36:00.1293974Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1294614Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_algorithms.py
2023-07-11T19:36:00.1295025Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1295488Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_arrays.py _
2023-07-11T19:36:00.1295774Z import file mismatch:
2023-07-11T19:36:00.1296304Z imported module 'pydatastructs.linear_data_structures.tests.test_arrays' has this __file__ attribute:
2023-07-11T19:36:00.1296728Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/linear_data_structures/tests/test_arrays.py
2023-07-11T19:36:00.1297068Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1297556Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_arrays.py
2023-07-11T19:36:00.1297974Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1298462Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_linked_lists.py _
2023-07-11T19:36:00.1298753Z import file mismatch:
2023-07-11T19:36:00.1299153Z imported module 'pydatastructs.linear_data_structures.tests.test_linked_lists' has this __file__ attribute:
2023-07-11T19:36:00.1299571Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/linear_data_structures/tests/test_linked_lists.py
2023-07-11T19:36:00.1299917Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1300405Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_linked_lists.py
2023-07-11T19:36:00.1300821Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1301332Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py _
2023-07-11T19:36:00.1301650Z import file mismatch:
2023-07-11T19:36:00.1302060Z imported module 'pydatastructs.linear_data_structures.tests.benchmarks.test_algorithms' has this __file__ attribute:
2023-07-11T19:36:00.1302512Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
2023-07-11T19:36:00.1302863Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1303369Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
2023-07-11T19:36:00.1303793Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1304294Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_arrays.py _
2023-07-11T19:36:00.1304737Z import file mismatch:
2023-07-11T19:36:00.1305150Z imported module 'pydatastructs.linear_data_structures.tests.benchmarks.test_arrays' has this __file__ attribute:
2023-07-11T19:36:00.1305591Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/linear_data_structures/tests/benchmarks/test_arrays.py
2023-07-11T19:36:00.1305938Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1306449Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_arrays.py
2023-07-11T19:36:00.1306858Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1307365Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_binomial_trees.py _
2023-07-11T19:36:00.1307690Z import file mismatch:
2023-07-11T19:36:00.1308098Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_binomial_trees' has this __file__ attribute:
2023-07-11T19:36:00.1308545Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_binomial_trees.py
2023-07-11T19:36:00.1308897Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1309419Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_binomial_trees.py
2023-07-11T19:36:00.1309826Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1310451Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_queue.py _
2023-07-11T19:36:00.1310776Z import file mismatch:
2023-07-11T19:36:00.1311191Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_queue' has this __file__ attribute:
2023-07-11T19:36:00.1311598Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_queue.py
2023-07-11T19:36:00.1311923Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1312422Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_queue.py
2023-07-11T19:36:00.1312837Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1313335Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py _
2023-07-11T19:36:00.1313702Z import file mismatch:
2023-07-11T19:36:00.1314143Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_range_query_static' has this __file__ attribute:
2023-07-11T19:36:00.1314579Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py
2023-07-11T19:36:00.1314944Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1315473Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py
2023-07-11T19:36:00.1315903Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1316392Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py _
2023-07-11T19:36:00.1316706Z import file mismatch:
2023-07-11T19:36:00.1317127Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_disjoint_set' has this __file__ attribute:
2023-07-11T19:36:00.1317572Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
2023-07-11T19:36:00.1317905Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1318582Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
2023-07-11T19:36:00.1319002Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1319481Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_multiset.py _
2023-07-11T19:36:00.1319795Z import file mismatch:
2023-07-11T19:36:00.1320201Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_multiset' has this __file__ attribute:
2023-07-11T19:36:00.1320638Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_multiset.py
2023-07-11T19:36:00.1320966Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1321476Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_multiset.py
2023-07-11T19:36:00.1321901Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1322416Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_dynamic.py _
2023-07-11T19:36:00.1322728Z import file mismatch:
2023-07-11T19:36:00.1323162Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_range_query_dynamic' has this __file__ attribute:
2023-07-11T19:36:00.1323609Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_range_query_dynamic.py
2023-07-11T19:36:00.1324066Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1324588Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_dynamic.py
2023-07-11T19:36:00.1325002Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1325480Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_stack.py _
2023-07-11T19:36:00.1325766Z import file mismatch:
2023-07-11T19:36:00.1326160Z imported module 'pydatastructs.miscellaneous_data_structures.tests.test_stack' has this __file__ attribute:
2023-07-11T19:36:00.1330800Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/miscellaneous_data_structures/tests/test_stack.py
2023-07-11T19:36:00.1331156Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1331707Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_stack.py
2023-07-11T19:36:00.1332115Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1332562Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_m_ary_trees.py _
2023-07-11T19:36:00.1332841Z import file mismatch:
2023-07-11T19:36:00.1333188Z imported module 'pydatastructs.trees.tests.test_m_ary_trees' has this __file__ attribute:
2023-07-11T19:36:00.1333547Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/trees/tests/test_m_ary_trees.py
2023-07-11T19:36:00.1333859Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1334318Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_m_ary_trees.py
2023-07-11T19:36:00.1334709Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1335172Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_binary_trees.py _
2023-07-11T19:36:00.1335461Z import file mismatch:
2023-07-11T19:36:00.1335820Z imported module 'pydatastructs.trees.tests.test_binary_trees' has this __file__ attribute:
2023-07-11T19:36:00.1336425Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/trees/tests/test_binary_trees.py
2023-07-11T19:36:00.1336752Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1341446Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_binary_trees.py
2023-07-11T19:36:00.1342159Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1342861Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_space_partitioning_tree.py _
2023-07-11T19:36:00.1343274Z import file mismatch:
2023-07-11T19:36:00.1343803Z imported module 'pydatastructs.trees.tests.test_space_partitioning_tree' has this __file__ attribute:
2023-07-11T19:36:00.1344362Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/trees/tests/test_space_partitioning_tree.py
2023-07-11T19:36:00.1344821Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1345770Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_space_partitioning_tree.py
2023-07-11T19:36:00.1346217Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1346715Z _ ERROR collecting build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_heaps.py _
2023-07-11T19:36:00.1347039Z import file mismatch:
2023-07-11T19:36:00.1347765Z imported module 'pydatastructs.trees.tests.test_heaps' has this __file__ attribute:
2023-07-11T19:36:00.1348365Z   /home/runner/work/pydatastructs/pydatastructs/pydatastructs/trees/tests/test_heaps.py
2023-07-11T19:36:00.1349257Z which is not the same as the test file we want to collect:
2023-07-11T19:36:00.1349816Z   /home/runner/work/pydatastructs/pydatastructs/build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_heaps.py
2023-07-11T19:36:00.1350568Z HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
2023-07-11T19:36:00.1350905Z =========================== short test summary info ============================
2023-07-11T19:36:00.1351514Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_algorithms.py
2023-07-11T19:36:00.1352141Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_list.py
2023-07-11T19:36:00.1352811Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/graphs/tests/test_adjacency_matrix.py
2023-07-11T19:36:00.1353438Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_trie.py
2023-07-11T19:36:00.1354248Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/strings/tests/test_algorithms.py
2023-07-11T19:36:00.1354699Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_misc_util.py
2023-07-11T19:36:00.1355344Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/utils/tests/test_code_quality.py
2023-07-11T19:36:00.1356185Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_algorithms.py
2023-07-11T19:36:00.1356868Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_arrays.py
2023-07-11T19:36:00.1357366Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/test_linked_lists.py
2023-07-11T19:36:00.1358247Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_algorithms.py
2023-07-11T19:36:00.1358979Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/linear_data_structures/tests/benchmarks/test_arrays.py
2023-07-11T19:36:00.1359674Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_binomial_trees.py
2023-07-11T19:36:00.1360392Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_queue.py
2023-07-11T19:36:00.1361286Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_static.py
2023-07-11T19:36:00.1362153Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_disjoint_set.py
2023-07-11T19:36:00.1362843Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_multiset.py
2023-07-11T19:36:00.1364607Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_range_query_dynamic.py
2023-07-11T19:36:00.1365165Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/miscellaneous_data_structures/tests/test_stack.py
2023-07-11T19:36:00.1365642Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_m_ary_trees.py
2023-07-11T19:36:00.1366241Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_binary_trees.py
2023-07-11T19:36:00.1366711Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_space_partitioning_tree.py
2023-07-11T19:36:00.1367200Z ERROR build/lib.linux-x86_64-cpython-310/pydatastructs/trees/tests/test_heaps.py
2023-07-11T19:36:00.1368279Z !!!!!!!!!!!!!!!!!!! Interrupted: 23 errors during collection !!!!!!!!!!!!!!!!!!!
2023-07-11T19:36:00.1368637Z ============================== 23 errors in 0.62s ==============================
```

### PR DESCRIPTION
**Pull request by sak-codes**
#### References to other Issues or PRs or Relevant literature

Closes #541

### CODE REVIEW

**Comment by sak-codes** [comment]
I have renamed the old file so that we can add all O(n**2) sort algorithms under the same file.

**Review by czgdp1807 — CHANGES_REQUESTED** [review]
Should be fixed - https://github.com/codezonediitj/pydatastructs/issues/541 before merging.

**Comment by sak-codes** [comment]
The failing test is fixed. Please review.

**Comment by czgdp1807** [comment]
What was the issue by the way?

**Review by czgdp1807 — APPROVED** [review]

**Comment by sak-codes** [comment]
Thank you for merging. The issue was an incorrect root path.

**Pull request merged**
