### PR TITLE
Removed import from __future__

### LINKED ISSUE #56: Remove imports from `__future__`
#### Description of the problem

As we are not concerned with Python 2, removing the following lines,
```python
from __future__ import print_function, division
```
will be less confusing for the developers.

### PR DESCRIPTION
**Pull request by TarunTomar122**
Fixes #56 

#### Brief description of what is fixed or changed
Removed import from __future__ as it was unnecessary for python 3

### CODE REVIEW

**Comment by czgdp1807** [comment]
There are still some files which are still having imports `__future__`. Probably, you haven't updated your `master` branch locally.

**Comment by czgdp1807** [comment]
Why closed?

**Comment by TarunTomar122** [comment]
I will fix this and then make a new pull request sooner

**Comment by czgdp1807** [comment]
Rather than making a new pull request, update this only by pushing changes here.

**Comment by czgdp1807** [comment]
You can merge master branch(after updating it by pulling the changes) into your branch and resume working on it.
If things don't work out well while pushing you can use `--force` to update the remote branch.

**Comment by TarunTomar122** [comment]
How shall i update my forked branch with you master branch...Mine is still 2commits behind your master branch

**Comment by czgdp1807** [comment]
Follow the steps given below,

1. git checkout master
2. git pull origin master
3. git checkout Test
4. git merge master
5. # make updates to Test
6. git push origin_user Test

Here `origin` refers to the remote of our main repository and `origin_user` refers to the remote of your forked branch.

**Comment by TarunTomar122** [comment]
And how can i update the same pull request??
shall i make a pull request from test to your master

**Comment by TarunTomar122** [comment]
I think it's updated now plz take a look! i have made some Changes in Test Branches (i.e. removed Future imports from 5 Files)

**Comment by czgdp1807** [comment]
Make changes to `Test` branch locally and push the changes via remote of your forked branch using a command something like,
`git push <remote-of-your-forked-branch> <name-of-the-branch>`
By doing so, this PR will be updated automatically.

**Comment by czgdp1807** [comment]
Yes, it's updated.

**Comment by czgdp1807** [comment]
I think you forgot to remove the line from https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/trees/binary_trees.py
In fact, you can search for the line in the complete package by using `Ctrl+Shift+E` and remove them one by one from each of the file.

**Comment by TarunTomar122** [comment]
I think I have removed the line from all the files and there is no more such lines left in my latest commit already!

**Pull request merged**
