### PR TITLE
Quick sort Algorithm

### PR DESCRIPTION
**Pull request by Moddy2024**
#### Brief description of what is fixed or changed
ISSUE #273 FIXED and quicksort algorithm added in the linear data structures folder

### CODE REVIEW

**Comment by Moddy2024** [comment]
@robotjellyzone i am assigned to this issue and i have created a pull request please look into it

**Comment by czgdp1807** [comment]
I would request you to not spam the PR list. Please go through the README. Understand the code base before making a PR. Closing this for now.

**Comment by Moddy2024** [comment]
> I would request you to not spam the PR list. Please go through the README. Understand the code base before making a PR. Closing this for now.

@czgdp1807 can you explain to me more what type of code base do you want ?

**Comment by czgdp1807** [comment]
You can see the existing code to understand the pattern. There are modules for better organisation of the code. Spend sometime understanding it. See https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects
Discussions are better and more important than directly jumping on implementations.

**Pull request closed without merging**
