### PR TITLE
Starting code for c++ backend of trees

### PR DESCRIPTION
**Pull request by Kishan-Ved**
#### References to other Issues or PRs or Relevant literature

Starting code for #550. This is more like a template.

#### Brief description of what is fixed or changed
This is some starting code for the trees backend. Honestly, some of this was written by ChatGPT, although I have understood and ensured that most of it is correct and necessary. Please check this and let me know if it is correct, so I can proceed with this. Also, please let me know what part has to be included in header file etc.

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
This might not seem like a lot of code addition, but I prefer making small PRs and getting  code verified atleast at the start.

**Comment by Kishan-Ved** [comment]
Gentle Reminder, please check this.

**Review by czgdp1807 — COMMENTED** [review]
LGTM. Please continue working on this.

**Comment by czgdp1807** [comment]
Looks duplicate of #555. Closing this in favour of #555.

**Pull request closed without merging**
