### PR TITLE
Added Cartesian Tree

### LINKED ISSUE #106: Add Cartesian tree

### PR DESCRIPTION
**Pull request by ajaynair710**
Closes #106

### CODE REVIEW

**Comment by czgdp1807** [comment]
Please give a better title to the PR and add `Closes #106` in the OP.

**Comment by ajaynair710** [comment]
Closes #106

**Comment by czgdp1807** [comment]
Are you working on it?

**Comment by HarsheetKakar** [comment]
is anyone working on it?

**Comment by czgdp1807** [comment]
Closing it due to inactivity.

**Pull request closed without merging**
