### PR TITLE
#64 Use comparision by reference for bool type objects

### PR DESCRIPTION
**Pull request by Saptashrungi**
Fixes https://github.com/codezonediitj/pydatastructs/issues/64
Replaced all == 'bool type' with is 'bool type' and similarly replaced != 'bool type' with is not 'bool type'.

### CODE REVIEW

**Comment by Saptashrungi** [comment]
Consider the second commit only with the name:

fd9dc53

**Comment by czgdp1807** [comment]
LGTM.
Just remove `.vs` files and push the updates to your `addis` branch. This PR will be automatically updated. Do not close this PR.

**Comment by czgdp1807** [comment]
> Consider the second commit only with the name:

We squash and merge commits so that won't be a problem. The [overall diff](https://github.com/codezonediitj/pydatastructs/pull/66/files) is fine.

**Comment by czgdp1807** [comment]
Thanks. Merging.
From next time onward, please do not clear the PULL REQUEST TEMPLATE, instead follow it and fill it. See previously merged PRs for examples.

**Pull request merged**
