### PR TITLE
Added cocktail shaker sort

### LINKED ISSUE #198: Cocktail Sort
#### Description of the problem

The code added sorts the array of numbers with minimum complexity as compared to bubble sort.

#### References/Other comments
https://en.wikipedia.org/wiki/Cocktail_shaker_sort

### PR DESCRIPTION
**Pull request by Arvind-raj06**
#### References to other Issues or PRs or Relevant literature
Closes #198.

#### Brief description of what is fixed or changed
Implementation of the Cocktail Shaker sort in this pull request in reference to the site https://www.sanfoundry.com/python-program-implement-cocktail-shaker-sort/

#### Other comments
I hope the description is quite useful and if you find any issue with this ping me.....

### CODE REVIEW

**Review by atarax665 — APPROVED** [review]

**Comment by czgdp1807** [comment]
Please add tests. See `linear_data_structures/tests/test_algorithms.py` for pattern of testing followed for sorting algorithms.

**Comment by Arvind-raj06** [comment]
Yeah process done

**Review by plazzy99 — APPROVED** [review]

**Comment by Arvind-raj06** [comment]
@czgdp1807 Is there any other improvements needed !?

**Comment by czgdp1807** [comment]
@Arvind-raj06 Are you contributing through SWOC-2021? Or any other open source program?

**Comment by Arvind-raj06** [comment]
Yes through SWOC

**Comment by Arvind-raj06** [comment]
Before this I didn't knew that there is project on python! I just determined myself to work on this one. There are a few projects on py in SWOC this one really awesome

**Pull request merged**
