### PR TITLE
Create B_tree.py

### PR DESCRIPTION
**Pull request by Amitsharma45**
#175 

#### Brief description of what is fixed or changed
i crate pprogram to implement B tree in python
#### Other comments
simple input :
Templates for commands are as follows:(this assumes no duplicate keys)
To add data at root enter:- add <data> at root
To add data below another data enter:- add <data> below <data>
To remove/delete data enter:- remove <data>
To display the Btree enter:- display
To end the process enter:- quit
What would you like to do? add 1 at root
What would you like to do? add 2 below 1
What would you like to do? add 3 below 1
What would you like to do? add 4 below 2
What would you like to do? add 5 below 2
What would you like to do? display
BFS traversal display: 1 2 3 4 5 
What would you like to do? remove 1
What would you like to do? display
BFS traversal display: 4 2 3 5 
What would you like to do? remove 5
What would you like to do? display
BFS traversal display: 4 2 3 
What would you like to do? remove 4
What would you like to do? display
BFS traversal display: 2 3 
What would you like to do? remove 3
What would you like to do? remove 2
What would you like to do? display
Tree is empty.
What would you like to do? quit

### CODE REVIEW

**Comment by czgdp1807** [comment]
Closing in reference to https://github.com/codezonediitj/pydatastructs/wiki/Pull-Request-Policy#when-to-close-a-pr

**Comment by Amitsharma45** [comment]
@czgdp1807 why you close pr

**Comment by Amitsharma45** [comment]
@czgdp1807 please tell my mistakes in pr

**Comment by robotjellyzone** [comment]
Hi @Amitsharma45 you first need to discuss about this solution before sending a PR . There was alreday a discussion on this please first try to discuss on it and then proceed. You should follow along the discussion here at #175 .also please follow the PR policy as said by @czgdp1807 in the above said statements ...

**Pull request closed without merging**
