### PR TITLE
Parameter order changed in docstrings

### LINKED ISSUE #251: Correct order of parameters in doc strings
#### Description of the problem

As of now, the order of `Parameters` in docstrings of classes/functions doesn't align with the order required in their prototype. For example, `TreeNode(key, data=None)` then the order of parameters in doc strings should be,
```
Parameters
=========

key
...

data
...
```

and NOT,

```
Parameters
=========

data
...

key
...
```
All doc strings should be checked for this consistency for closing this issue.

### PR DESCRIPTION
**Pull request by Ryand1234**
#### References to other Issues or PRs or Relevant literature
Fixes #251 

#### Brief description of what is fixed or changed
Order of parameter in docstring now matches their prototype function/class.

### CODE REVIEW

**Comment by czgdp1807** [comment]
Looks good, some minor changes are needed. Are you a GSSoC, 2020 participant.

**Comment by Ryand1234** [comment]
No, I'm not a participant

**Comment by Ryand1234** [comment]
What changes are needed?

**Comment by czgdp1807** [comment]
IMO, changes would be too subtle. Merging directly.

**Comment by czgdp1807** [comment]
Thanks.

**Pull request merged**
